### ISSUE TITLE
When using 'completed' property of series object, animating a graphic (for instance on/off behavior of legend items) causes console errors and unresponsive behavior

### ISSUE THREAD

**Issue by fabianvanhummel93** [jscharting/jscharting-dist#12]
https://jscharting.com/examples/chart-types/gantt/complex/ looking at this example, reproduce by:
- Open dev console
- Activate anything that causes bar opacity events to happen (for instance, clicking a legend item)
- See the console errors flowing in

**Comment by arthurPuszynski** [comment]
Thank you for the bug report. We addressed this issue and the fix will be available in the next update. If you would like a fixed bundle now, please contact support at jscharting.com.

Regards,
Arthur Puszynski
