### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by bilogic** [jscharting/jscharting-dist#17]
![image](https://github.com/jscharting/jscharting-dist/assets/946010/c0ae12e2-18e0-4980-8101-71238c3773d4)

https://jscharting.com/examples/chart-types/linear-gauge/horizontal-sleep-gantt/
How do I change the color of the grey in the red box?

**Comment by arthurPuszynski** [comment]
Hello,
The easiest way would be to add a series with two data points spanning those red rectangles. 

See this example: https://codepen.io/jsblog/pen/poBRjWE
Note the changes on lines 47 and 311

Regards,
Arthur Puszynski

**Comment by bilogic** [comment]
@arthurPuszynski thanks, but that also adds `extra` to the legend, I was looking more to really color the entire unfilled region of the bar. 

My main purpose here is to replace it with a color friendlier to dark themes. Perhaps a class could be added so that I can target it with CSS?

**Comment by arthurPuszynski** [comment]
You can modify this color with this setting: xAxis_defaultTick_gridLine_color:'blue',

Regards,
Arthur Puszynski

**Comment by bilogic** [comment]
Thanks! Just want to add that it should be nested as `xAxis.defaultTick.gridLine.color`.
But it doesn't seem to accept `'rgba(255, 0, 255, 255)'`, whereas `box.fill` does. Is this by design?

**Comment by bilogic** [comment]
Nevermind, I realized opacity can be controlled by `xAxis.defaultTick.gridLine.opacity`.
