### ISSUE TITLE
SyntaxError: expected expression, got '<' jscharting React js

### ISSUE THREAD

**Issue by rajatmadaan786** [jscharting/jscharting-dist#2]
Getting **"SyntaxError: expected expression, got '<' jscharting React js"** error don't know why.

Below is the screenshot of it.

![chart-error](https://user-images.githubusercontent.com/60581494/92735222-dd336b80-f396-11ea-8d30-60c8f11f1919.PNG)

**Comment by arthurPuszynski** [comment]
Hello, 
I suspect that the chart may be trying to load a module script that is not available and your server responds with an html page that it's trying to evaluate. Please see this section https://github.com/jscharting/jscharting-react#chart-resources for details on how to set up the chart and give it access to the resources it needs in react.

But if this is not helpful, would it be possible to send me a repo for this error, perhaps a link where I can run this page? You can send it to [support](https://jscharting.com/support.htm) directly. 

Thank you

**Comment by rajatmadaan786** [comment]
I have tried **"jscharting-react"** but it's not working as expected. "jscharting" npm package is good for me but I am getting error in it. You can get more detail about the error and full code on the StackOverflow question.

https://stackoverflow.com/questions/63825768/syntaxerror-expected-expression-got-jscharting-react-js

**Comment by rajatmadaan786** [comment]
@arthurPuszynski , I liked [this](https://www.npmjs.com/package/jscharting) npm package for displaying charts in my react js web app and I am using that in my code I have shared with you guys in which currently I am facing the above issue. 

Isn't there any way that we can get the above issue fixed? Also, there's one more issue in "jscharting" package. After parsing data from the CSV file, On the first load, the chart doesn't render its graphics(lines,bars, etc.). I think that are the major issues and they should get fixed ASAP. 

Thank you.

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 I tried to replicate the issue with the code but am having trouble getting the same result. So I tried to simplify it and replicate it here: https://codepen.io/jsblog/pen/vYGrrbv

The problem in this sample is the CORS policy on yahoo. If this is not the issue and you are able to make the data download, please update this codepen and I can dig into it further. I will be able to help you figure this out once I am able to replicate the issue.

**Comment by rajatmadaan786** [comment]
Please forget about the CORS error for now. We can fix it by installing a chrome or firefox extension for development purposes. 
And The codepen link you have shared with me is working fine without any console error.

But I don't think, You have used "jscharting" npm package for that. I am using that inside my react js code and getting error in that. You can try to use the code I have shared with you in the react app and you will get the same errors I am getting.

Thanks

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 If you are able to get the csv data without issue then please make sure the './js/jsc/modules/types.js' path returns a javascript file per this setting: `JSC.defaults({ baseUrl: './js/jsc/' });` 

Unfortunately I am not able to replicate the same results with the react code you provided. If you can send me a stand-alone project I can to replicate it, I'll be able to help more. Please send it to support at jscharting.com

**Comment by rajatmadaan786** [comment]
No sir, This path doesn't exist in my 'jscharting' npm package. Below are my jscharting package node modules images.

![node-modules-1](https://user-images.githubusercontent.com/60581494/93270918-b11d4d80-f7cf-11ea-8348-de432ac18185.PNG)
![node-module-2](https://user-images.githubusercontent.com/60581494/93270912-aebaf380-f7cf-11ea-93ac-4482d2626680.PNG)

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 Oh I see. In order to use all the extra modules in JSC there is an extra step you need to take. Using webpack or any bundler tool that you use, you must include a step to copy `node_modules/jscharting/dist/` to a directory that is available in the built output and accessible through https address. 

This is an example of this from the jscharting-react project:
https://github.com/jscharting/jscharting-react/blob/master/examples/webpack.config.js#L45

```
{
				from: 'node_modules/jscharting/dist/',
				to: 'assets/jscharting/',
				ignore: ['jscharting.*']
			}
```

Then in this line JSC.defaults({ baseUrl: './js/jsc/' }) specify the URL to that https address. JSC basically looks at this address, adds it to the current url to request additional modules it needs. 

Please let me know if this doesn't resolve your issue.

**Comment by rajatmadaan786** [comment]
I really appreciate your help. But sir are you sure that, It's looking for the file inside dist?
And in actual, I didn't get what you want me to do sir. As I never used webpack or any other bundler tool before.

Can you please tell me in a bit more detail?

Thank you :)

**Comment by rajatmadaan786** [comment]
@arthurPuszynski, Are you still available to help?

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 Sorry, yes.. In that case, at least to get started you can manually copy the contents of node_modules/jscharting/dist/ folder to a folder that is accessible inside your application at runtime. 

For example if your app is `https://yourApp/` and `https://yourApp/js/jsc/` maps to `e:/.../yourApp/js/jsc/` and you copy those files there, then the `JSC.defaults({ baseUrl: './js/jsc/' })` setting should make it work. 

Does that make sense?

**Comment by rajatmadaan786** [comment]
dist folder size is around 37 MB. Don't you think, If I will use webpack to import the dist folder or directly copy paste dist folder content into my app then it will make my application almost impossible to load or load with after too much delay.

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 If it's not as fast as you need it, you dont have to copy all the files in there. 

![image](https://user-images.githubusercontent.com/16340150/93818371-e5ee3200-fc1f-11ea-982c-b0444e523325.png)

`polyfill/` you only need to support much older browsers. The `locales/` folder you probably wont need to use. That's most of the size. 
`resources/` is required only for mapping data.
The rest is small.

**Comment by rajatmadaan786** [comment]
The "SyntaxError: expected expression, got '<' jscharting" issue has fixed. Thank you so much, sir :)

But sir, I wanna use webpack to import jscharting inside my project instead of copy and paste dist folder from node_modules and import it in my file. Can you please share any reference video of How we can achieve the same? I will really appreciate the same. 

**Note:** But I am still conscious about the size of my webpage first load. If we import all 36 MB folder in the file then how will it react.

Thank you again :)

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 Please see this example react project: https://github.com/jscharting/jscharting-react to see how to do this with react. Or you can see this webpack example: https://github.com/jscharting/jscharting-webpack

**Comment by rajatmadaan786** [comment]
@arthurPuszynski  Need one more help, Sir. Actually, I want to make the **defaultTooltip** prop data dynamic.

    JSC.chart(chartId, {
	    type: "line",
	    legend_position: "inside bottom right",
	    xAxis: { scale_type: "time" },
	    series: [
		 {
		       points: data
		 }
	    ],
 	   defaultTooltip:{
		combined:"true",
		label_text:"<b>%x10</b><br>%points"
	    }
    });

I want to put the dynamic content coming from my DB into the **label_text** field. Tried different ways to do that and searched in the docs but didn't found any way. 

Can you please help me with that also?

Thank you.

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 Sure, you can store extra data attributes in point data as shown here: https://jscharting.com/tutorials/js-chart-labels/data-labels/#point-attribute-tokens

Then you can use this to display it in tooltips:

```
defaultPoint_tooltip:'%attributeName %yValue' 
```

Does that make sense?

**Comment by rajatmadaan786** [comment]
First of all, Thanks for your quick reply. As you said, I have to store extra data attributes in the point data. But in my case, I didn't stored any data attribute in points then how it's showing me data in tooltip?

Here's my chart configs:

     JSC.chart(chartId, {
		type: "line",
		legend_position: "inside bottom right",
		xAxis: { scale_type: "time" },
		series: [
			{
			    points: data
			}
		],
		defaultTooltip:{
			combined:"true",
			label_text:"<b>%xValue</b><br>%points"
		}
	});

And Here's How my data variable looks like:

```
[
 	["2019-09-09", 1204.410034]
	["2019-09-10", 1206]
	["2019-09-11", 1220.170044]
]
```

And tooltip is showing me like this.
![Capture](https://user-images.githubusercontent.com/60581494/94177594-6c707100-feb7-11ea-982a-73361b9d8993.PNG)

I didn't understand the label_text field completely. what %x is and from where Value came and what's %points. Can you please help me to resolve this?

Thank you.

**Comment by arthurPuszynski** [comment]
@rajatmadaan786 It's only showing the point data that is available in tooltips. It's the default behavior. 

The last "combined tooltip" section here explains how to configure the combined tooltips: 
https://jscharting.com/tutorials/js-chart-interactivity/crosshair-combined-tooltip/

I am not sure what you mean by %x. But %xValue refers to the x value at a specific x position, and %points refers to the individual tooltip of each point at that x position (If you have multiple line series, you'll see multiple points there). In this case there is only one series so only one point y value is shown. You control the individual point tooltips with something like defaultPoint_tooltip:'%icon %yValue' .

That's what your image above is showing.
